# Generated by Django 4.1.2 on 2022-10-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hepsiburada',
            name='ekran_boyutu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hepsiburada',
            name='islemci',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hepsiburada',
            name='islemci_tipi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hepsiburada',
            name='isletim_sistemi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hepsiburada',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hepsiburada',
            name='marka',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hepsiburada',
            name='model_adi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hepsiburada',
            name='puani',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hepsiburada',
            name='ram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hepsiburada',
            name='ssd_kapasitesi',
            field=models.CharField(max_length=100),
        ),
    ]
